- docs/README.md
Thanks to Dan in PR : https://github.com/soal/vue-mapbox/pull/128
Co-Authored-By: Dan Shields <dan@chips.nyc>
> fix: typo in docs

- docs/README.md
Thanks to @signalwerk
Co-Authored-By: Stefan Huber <sh@signalwerk.ch>
> fix: update typo in docs

- docs/guide/README.md
- docs/guide/basemap.md
> docs: add ES Module import css example

- docs/README.md
Co-Authored-By: Abu Uzayr <abu.uzayr@builtforfifty.com>
> refactor: update docs

- docs/api/popup.md
> fix: update docs for Popup open & close events

- docs/api/Layers/README.md
Thanks to @pierremonico for the original PR https://github.com/soal/vue-mapbox/pull/151
Co-Authored-By: Pierre Monico <pierremonico@users.noreply.github.com>
> fix: update README for Layers

- src/components/map/events.js
https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:styleimagemissing
> feat: add styleimagemissing event

- jsconfig.json
> feat: enable jsconfig for better VSCode Intellisense

- docs/guide/composition.md
Co-Authored-By: Almond Valleza <mavalleza@users.noreply.github.com>
> fix(docs): update grammar of composition

- docs/api/popup.md
- src/components/UI/Popup.vue
Hi, not sure if you're open to pull requests
I've implemented the `className` option of the popup, this is not reactive
> feat: add className option to popup

- src/components/UI/Popup.vue
Co-Authored-By: Kyle <1763574+Kyle123@users.noreply.github.com>
> fix: add classes for popup

- src/components/map/mixins/withPrivateMethods.js
synced from https://github.com/soal/vue-mapbox/commit/7ed51b8afe4bebb2333db0fdf0d9fe5dd42cbc10
> feat: make 'bounds' synced prop

- src/components/map/GlMap.vue
Thanks for https://github.com/soal/vue-mapbox/pull/199
Co-Authored-By: a-allababidi <48721341+a-allababidi@users.noreply.github.com>
> fix: rtl issue

- .github/dependabot.yml
- .github/workflows/shipjs-trigger.yml
- package-lock.json
- package.json
> fix: minor housekeeping

- package.json
> fix: the `main` entry file was 404

- build/rollup.config.js
- build/rollup.config.min.js
- package-lock.json
- package.json
- src/components/map/GlMap.vue
> fix: css issue caused due to `sideEffects: false`

- docs/api/popup.md
- docs/guide/markers&popups.md
- src/components/UI/Popup.vue
> feat: add `closeOnMove` & `focusAfterOpen` props

- src/components/UI/Popup.vue
Co-Authored-By: helenezspeer <5831237+helenezspeer@users.noreply.github.com>
> fix: prop "showed" in popup caused cyclic issue

- docs/guide/basemap.md
- src/components/UI/Popup.vue
Small fix to change a typo: deafult to default
> fix: typo deafult to default

- docs/api/controls.md
- src/components/UI/controls/GeolocateControl.js
- src/components/UI/controls/NavigationControl.js
just to be closer to mapbox/maplibre API
(I hate commitLint !)
> fix: add props reflecting Mapbox Control API

- docs/api/controls.md
- src/components/UI/controls/controlMixin.js
- Closes #362
Co-Authored-By: Marco <292021+elmatou@users.noreply.github.com>
> fix: watcher for control position

- src/components/layer/layerMixin.js
Co-Authored-By: helenezspeer <5831237+helenezspeer@users.noreply.github.com>
> fix: before prop reactive

- docs/api/controls.md
- src/components/UI/controls/IControl.ts
- src/index.ts
> feat: add iControl Component

- src/components/UI/Marker.vue
- src/components/UI/Popup.vue
- src/components/map/GlMap.vue
- Closes https://github.com/geospoc/v-mapbox/pull/653
> fix: scope the `hidden` class to avoid conflict with tailwind

- README.md
- build/rollup.config.min.ts
- build/rollup.config.ts
- package-lock.json
- package.json
> docs: add codesandbox with DeckGL demo

- types/index.d.ts
- types/layers/deck.gl/VLayerDeckArc.vue.d.ts
- types/layers/deck.gl/VLayerDeckGeojson.vue.d.ts
- types/layers/mapbox/VLayerMapboxGeojson.vue.d.ts
- types/layers/mapbox/VLayerMapboxImage.vue.d.ts
- types/layers/mapbox/VLayerMapboxRaster.vue.d.ts
- types/layers/mapbox/VLayerMapboxVector.vue.d.ts
- types/layers/mapbox/VLayerMapboxVideo.vue.d.ts
> fix: generate new typings using `vue-tsc`

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/shipjs-trigger.yml
- package-lock.json
- package.json
- src/layers/mapbox/VLayerMapboxGeojson.vue
- src/map/VMap.vue
- tsconfig.json
- types/layers/mapbox/VLayerMapboxGeojson.vue.d.ts
- types/popups/VPopup.vue.d.ts
> feat: enable passing the `GeoJSONSourceRaw` as `prop`

- src/layers/mapbox/VLayerMapboxGeojson.vue
- src/map/VMap.vue
- types/layers/mapbox/VLayerMapboxGeojson.vue.d.ts
- types/map/VMap.vue.d.ts
> fix(geojson): clean up of props 📍

- src/layers/mapbox/VLayerMapboxGeojson.vue
- src/markers/VMarker.vue
- src/popups/VPopup.vue
Signed-off-by: Vinayak Kulkarni <19776877+vinayakkulkarni@users.noreply.github.com>
> fix: minor housekeeping 🎉

- .github/dependabot.yml
- .vscode/settings.json
- CODE_OF_CONDUCT.md
- LICENSE
- package-lock.json
- package.json
- shims/@rollup/plugin-beep.d.ts
- ship.config.cjs
Signed-off-by: Vinayak Kulkarni <19776877+vinayakkulkarni@users.noreply.github.com>
> chore: update config files & remove stale config file(s)

- .github/workflows/automerger.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/ct.yml
- .github/workflows/pipeline.yml
- package-lock.json
- package.json
- test/map/VMap.spec.ts
- test/markers/VMarker.spec.ts
- test/popups/VPopup.spec.ts
- test/setup/index.ts
- tsconfig.json
- vite-env.d.ts
- vitest.config.ts
Signed-off-by: Vinayak Kulkarni <19776877+vinayakkulkarni@users.noreply.github.com>
> test: add Vitest 🧪
